# Generated by Django 5.2.17 on 2026-09-09 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_employeedocument'),
        ('organization', '0004_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=150)),
                ('model_number', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('lost', 'Lost')], db_index=True, default='available', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organization.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('condition_at_allocation', models.CharField(default='good', max_length=50)),
                ('condition_at_return', models.CharField(blank=True, default='', max_length=50)),
                ('allocation_notes', models.TextField(blank=True, default='')),
                ('return_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'is_active'], name='assets_asse_asset_i_4e48bb_idx'), models.Index(fields=['employee', 'is_active'], name='assets_asse_employe_b2486a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset',), name='unique_active_asset_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['organization', 'is_active'], name='assets_asse_organiz_26edae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('organization', 'code'), ('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='assets_asse_organiz_ad90f0_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'category'], name='assets_asse_organiz_26a143_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'asset_tag')},
        ),
    ]
