# Generated by Django 5.2.17 on 2026-09-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_check_in_accuracy_and_more'),
        ('employees', '0010_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='full_day_hours',
            field=models.DurationField(blank=True, help_text='Minimum hours for a full day', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='half_day_hours',
            field=models.DurationField(blank=True, help_text='Minimum hours for a half day', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Comma-separated integers for work days (0=Mon, 6=Sun)', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__gte', models.F('effective_from')), ('effective_to__isnull', True), _connector='OR'), name='check_valid_effective_dates')],
            },
        ),
    ]
