# Generated by Django 6.1 on 2026-09-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_seed_shift_permissions'),
        ('organization', '0007_attendancepolicy_branch_officenetwork_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('organization', 'name')},
        ),
        migrations.AddField(
            model_name='holiday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_holidays', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_shifts', to='organization.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('branch', 'date'), ('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('branch', 'name'), ('organization', 'name')},
        ),
    ]
