# Generated by Django 6.1 on 2026-09-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_holiday_unique_together_and_more'),
        ('organization', '0009_remove_attendancepolicy_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('branch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.branch'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='organization',
        ),
    ]
