# Generated by Django 6.1 on 2026-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_seed_attendance_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
