# Generated by Django 6.1 on 2026-09-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text="Categorization code (e.g., 'LEAVE_APPROVED', 'PAYSLIP_ISSUED')", max_length=50)),
                ('title', models.CharField(help_text='Short summary of the notification', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification content')),
                ('reference_id', models.CharField(blank=True, help_text='Optional identifier of the related object (e.g., LeaveRequest ID). Not a strict foreign key to allow safe deletion of referenced objects.', max_length=150)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has viewed this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization context. Null for global/system notifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.organization')),
                ('recipient', models.ForeignKey(help_text='The user receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['organization', '-created_at'], name='notificatio_organiz_f822ba_idx')],
            },
        ),
    ]
