# Generated by Django 6.1 on 2026-09-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organization', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(help_text='The organization context.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.organization'),
        ),
    ]
