# Generated by Django 5.2.17 on 2026-10-08 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetype',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
