# Generated by Django 5.2.17 on 2026-09-08 09:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_employee_branch'),
        ('organization', '0004_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='organization.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.PositiveSmallIntegerField(help_text='Total scheduled working days in the period (excl. weekends & holidays)')),
                ('present_days', models.PositiveSmallIntegerField(help_text='Days with Attendance status=present')),
                ('half_days', models.PositiveSmallIntegerField(default=0, help_text='Days with Attendance status=half_day (counted as 0.5)')),
                ('absent_days', models.PositiveSmallIntegerField(help_text='working_days - present_days - half_days - leave_days')),
                ('leave_days', models.PositiveSmallIntegerField(help_text='Approved leave days overlapping the period (already weekday/holiday excluded)')),
                ('effective_days', models.DecimalField(decimal_places=1, help_text='present + (half_days * 0.5) + leave_days — paid days', max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Monthly basic salary as of period start', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='basic_salary × (effective_days / working_days)', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Equals gross_salary (no statutory deductions in current scope)', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['employee__employee_code'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
