# Generated by Django 5.2.17 on 2026-09-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_seed_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(db_index=True, help_text='Format: PAY-YYYYMM-EMPLOYEE_CODE', max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='payroll.payrollrecord')),
            ],
            options={
                'ordering': ['-payroll_record__period__year', '-payroll_record__period__month', 'payroll_record__employee__employee_code'],
                'indexes': [models.Index(fields=['payslip_number'], name='payroll_pay_payslip_7dfc92_idx'), models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx')],
            },
        ),
    ]
