# Generated by Django 5.2.17 on 2026-10-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payrollrun_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolllineitem',
            name='calculation_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrolllineitem',
            name='calculation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payrolllineitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='lop_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of YYYY-MM-DD strings where employee was marked absent/LOP'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_version',
            field=models.CharField(default='v1', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrolllineitem',
            name='source_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.payrolladjustment'),
        ),
        migrations.AlterField(
            model_name='payrolllineitem',
            name='source_structure_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.salarystructurecomponent'),
        ),
    ]
