# Generated by Django 5.2.17 on 2026-10-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organizationmembership'),
        ('payroll', '0008_payrolllineitem_calculation_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PF', 'Provident Fund'), ('ESI', 'Employee State Insurance'), ('PT', 'Professional Tax'), ('TDS', 'Tax Deducted at Source')], max_length=10)),
                ('state', models.CharField(blank=True, help_text='Required for PT', max_length=50, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=0, help_text='e.g. 12.00 for PF', max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=0, help_text='e.g. 13.00 for PF (12 + 1 EDLI/Admin)', max_digits=5)),
                ('applicable_limit', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 15000 for PF, 21000 for ESI', max_digits=12, null=True)),
                ('rule_metadata', models.JSONField(blank=True, default=dict, help_text='For complex structures like PT slabs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
