# Generated by Django 6.1 on 2026-09-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('organization', '0007_attendancepolicy_branch_officenetwork_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissiongrant',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='userpermissiongrant',
            name='scope',
            field=models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch')], default='organization', max_length=20),
        ),
        migrations.AddField(
            model_name='userrole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope',
            field=models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch')], default='organization', max_length=20),
        ),
    ]
