# Generated by Django 6.1 on 2026-09-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userpermissiongrant_branch_userpermissiongrant_scope_and_more'),
        ('organization', '0010_alter_department_unique_together_department_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissiongrant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.team'),
        ),
        migrations.AlterField(
            model_name='userpermissiongrant',
            name='scope',
            field=models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch'), ('team', 'Team')], default='organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='scope',
            field=models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch'), ('team', 'Team')], default='organization', max_length=20),
        ),
    ]
