# Generated by Django 6.1 on 2026-09-16 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_userpermissiongrant_team_and_more'),
        ('organization', '0010_alter_department_unique_together_department_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.team'),
        ),
    ]
