# Generated by Django 6.1.1 on 2026-09-29 06:05

import apps.candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_employee_team'),
        ('organization', '0011_workingcalendarrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text="Candidate's personal/contact email", max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('proposed_joining_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('offered', 'Offer Sent'), ('onboarding', 'Onboarding'), ('submitted', 'Submitted'), ('verifying', 'Under Verification'), ('approved', 'Approved'), ('converted', 'Converted to Employee'), ('rejected', 'Rejected')], db_index=True, default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='organization.designation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(blank=True, help_text='Populated after conversion. Establishes candidate→employee traceability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_record', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='organization.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Auth account created for the candidate onboarding portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', 'Identity Proof'), ('address', 'Address Proof'), ('education', 'Education Certificate'), ('employment', 'Previous Employment Proof'), ('other', 'Other')], default='other', max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.candidates.models.candidate_document_upload_path)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOnboardingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_notes', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('offer', 'Offer Letter'), ('appointment', 'Appointment Letter')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Template body. Supports {{candidate_name}}, {{designation}}, {{joining_date}}, {{organization}} placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='organization.organization')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='IssuedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('offer', 'Offer Letter'), ('appointment', 'Appointment Letter')], max_length=30)),
                ('template_version', models.PositiveIntegerField(blank=True, help_text='Snapshot of template version number at issue time', null=True)),
                ('subject_snapshot', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField(help_text='Rendered/final letter body at issue time')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_letters', to='candidates.candidate')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_letters', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used at issue time (for reference only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_letters', to='candidates.lettertemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', 'status'], name='candidates__organiz_94090f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email', 'organization'], name='candidates__email_781e67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lettertemplate',
            unique_together={('organization', 'letter_type', 'version')},
        ),
    ]
