# Generated by Django 6.1 on 2026-08-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_wfhrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text="Employee's personal email for onboarding", max_length=254, null=True, unique=True),
        ),
    ]
