# Generated by Django 6.1 on 2026-09-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_department_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee'),
        ),
    ]
