# Generated by Django 6.1 on 2026-09-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeedocument'),
        ('organization', '0010_alter_department_unique_together_department_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.team'),
        ),
    ]
