# Generated by Django 5.2.17 on 2026-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='employer_pf_capped',
            field=models.BooleanField(default=True, help_text='Does employer cap their contribution at the wage limit?'),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='is_esi_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='is_pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='is_pt_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='pf_wage_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override statutory 15000 cap. Null means use statutory rule.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='tax_regime',
            field=models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='employeestatutoryinfo',
            name='vpf_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
