# Generated by Django 5.2.17 on 2026-08-19 07:15

import apps.organization.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('network', models.CharField(help_text='e.g., 203.0.113.0/24', max_length=45, validators=[apps.organization.models.validate_network])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_networks', to='organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'network')},
            },
        ),
    ]
