# Generated by Django 5.2.17 on 2026-09-15 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='radius',
            field=models.FloatField(default=100.0, help_text='Radius in meters', validators=[django.core.validators.MinValueValidator(100.0)]),
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_office_gps_enabled', models.BooleanField(default=True)),
                ('is_office_ip_enabled', models.BooleanField(default=False)),
                ('is_wfh_enabled', models.BooleanField(default=False)),
                ('wfh_bypasses_office_restrictions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='organization.organization')),
            ],
        ),
    ]
