# Generated by Django 5.2.17 on 2026-09-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_branch_radius_attendancepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.CharField(default='0,1,2,3,4', help_text='Comma separated integers (0=Monday, 6=Sunday)', max_length=50)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_calendar', to='organization.organization')),
            ],
        ),
    ]
