# Generated by Django 6.1 on 2026-09-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_workingcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='officenetwork',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_networks', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='workingcalendar',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_calendar', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_attendance_policies', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='officenetwork',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_office_networks', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_working_calendars', to='organization.organization'),
        ),
    ]
