# Generated by Django 6.1 on 2026-09-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_migrate_org_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancepolicy',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='officenetwork',
            unique_together={('branch', 'network')},
        ),
        migrations.RemoveField(
            model_name='workingcalendar',
            name='organization',
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='officenetwork',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_networks', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='workingcalendar',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_calendar', to='organization.branch'),
        ),
        migrations.RemoveField(
            model_name='officenetwork',
            name='organization',
        ),
    ]
