# Generated by Django 6.1 on 2026-09-16 11:42

import django.db.models.deletion
from django.db import migrations, models


def assign_departments_to_branch(apps, schema_editor):
    Department = apps.get_model('organization', 'Department')
    Branch = apps.get_model('organization', 'Branch')

    for dept in Department.objects.all():
        branches = Branch.objects.filter(organization_id=dept.organization_id)
        count = branches.count()
        if count == 0:
            raise Exception(
                f"Cannot map Department '{dept.name}' (ID {dept.id}): "
                f"Organization {dept.organization_id} has no branches."
            )
        elif count == 1:
            dept.branch = branches.first()
            dept.save()
        else:
            raise Exception(
                f"Cannot deterministically map Department '{dept.name}' (ID {dept.id}): "
                f"Organization {dept.organization_id} has multiple branches ({count})."
            )

def reverse_assign_departments(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeedocument'),
        ('organization', '0009_remove_attendancepolicy_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.branch'),
        ),
        migrations.RunPython(
            assign_departments_to_branch,
            reverse_code=reverse_assign_departments
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organization.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='employees.employee')),
            ],
            options={
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('branch', 'name')},
        ),
    ]
