# Generated by Django 6.1 on 2026-09-22 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_department_unique_together_department_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCalendarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(help_text='0=Monday, 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('occurrence', models.IntegerField(help_text='1=1st, 2=2nd, 3=3rd, 4=4th, 5=5th occurrence in the month', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_working', models.BooleanField(default=False, help_text='Whether this occurrence is a working day (True) or non-working day (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='organization.workingcalendar')),
            ],
            options={
                'ordering': ['weekday', 'occurrence'],
                'unique_together': {('working_calendar', 'weekday', 'occurrence')},
            },
        ),
    ]
