# Generated by Django 5.2.17 on 2026-10-06 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def backfill_memberships(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    OrganizationMembership = apps.get_model('organization', 'OrganizationMembership')
    
    # Create an active membership for every existing employee that has a user and organization
    memberships = []
    for emp in Employee.objects.filter(user__isnull=False, organization__isnull=False):
        if not OrganizationMembership.objects.filter(user=emp.user, organization=emp.organization).exists():
            memberships.append(OrganizationMembership(
                user=emp.user,
                organization=emp.organization,
                status='active'
            ))
    OrganizationMembership.objects.bulk_create(memberships)

def reverse_backfill(apps, schema_editor):
    OrganizationMembership = apps.get_model('organization', 'OrganizationMembership')
    OrganizationMembership.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_workingcalendarrule'),
        ('employees', '0013_employee_address_line1_employee_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(backfill_memberships, reverse_backfill),
    ]
