# Generated by Django 5.2.17 on 2026-09-07 11:09

from django.db import migrations


def backfill_leave_balances(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    LeaveType = apps.get_model('leaves', 'LeaveType')
    LeaveBalance = apps.get_model('leaves', 'LeaveBalance')

    balances_to_create = []
    
    # Get all employees with an organization
    employees = Employee.objects.exclude(organization__isnull=True)
    
    for emp in employees:
        # Get active leave types for this employee's organization
        leave_types = LeaveType.objects.filter(organization=emp.organization, is_active=True)
        for lt in leave_types:
            # Check if balance already exists
            if not LeaveBalance.objects.filter(employee=emp, leave_type=lt).exists():
                balances_to_create.append(
                    LeaveBalance(
                        employee=emp,
                        leave_type=lt,
                        allocated=lt.annual_allocation,
                        used=0
                    )
                )
                
    if balances_to_create:
        LeaveBalance.objects.bulk_create(balances_to_create)

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_leave_balances, reverse_backfill),
    ]
