# Generated by Django 6.1 on 2026-09-23 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_team'),
        ('leaves', '0002_auto_provision_balances'),
        ('organization', '0011_workingcalendarrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='annual_allocation',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='LeaveCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_cycles', to='organization.branch')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('legacy_conversion_allocated', 'Legacy Conversion Allocated'), ('legacy_conversion_used', 'Legacy Conversion Used'), ('allocation', 'Allocation'), ('monthly_accrual', 'Monthly Accrual'), ('proration', 'Proration'), ('carry_forward', 'Carry Forward'), ('usage', 'Usage (Leave Approved)'), ('refund', 'Refund (Leave Cancelled)'), ('manual_adjustment', 'Manual Adjustment'), ('carry_forward_expiry', 'Carry Forward Expiry'), ('exit_forfeiture', 'Exit Forfeiture'), ('branch_transfer_adjustment', 'Branch Transfer Adjustment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='leaves.leavebalance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_transactions', to='employees.employee')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
                ('leave_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.leavecycle')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaves.leavecycle'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'leave_cycle')},
        ),
        migrations.CreateModel(
            name='BranchLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_allocation', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('proration_enabled', models.BooleanField(default=True)),
                ('proration_rounding', models.CharField(choices=[('nearest_half', 'Nearest 0.5'), ('floor', 'Floor'), ('ceiling', 'Ceiling')], default='nearest_half', max_length=20)),
                ('carry_forward_enabled', models.BooleanField(default=False)),
                ('carry_forward_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carry_forward_expiry_months', models.PositiveIntegerField(blank=True, null=True)),
                ('negative_balance_allowed', models.BooleanField(default=False)),
                ('half_day_allowed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_supporting_document', models.BooleanField(default=False)),
                ('advance_notice_days', models.PositiveIntegerField(default=0)),
                ('cancellation_allowed', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.branch')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_policies', to='leaves.leavetype')),
            ],
            options={
                'unique_together': {('branch', 'leave_type')},
            },
        ),
    ]
