# Generated by Django 6.1 on 2026-09-23 11:59

from django.db import migrations

def convert_legacy_balances(apps, schema_editor):
    LeaveBalance = apps.get_model('leaves', 'LeaveBalance')
    LeaveBalanceTransaction = apps.get_model('leaves', 'LeaveBalanceTransaction')

    transactions = []
    for balance in LeaveBalance.objects.all():
        if balance.allocated > 0:
            transactions.append(
                LeaveBalanceTransaction(
                    balance=balance,
                    employee=balance.employee,
                    leave_type=balance.leave_type,
                    transaction_type='legacy_conversion_allocated',
                    amount=balance.allocated,
                    effective_date=None,
                    reference="Legacy conversion from pre-C6.3 LeaveBalance.allocated"
                )
            )
        if balance.used > 0:
            transactions.append(
                LeaveBalanceTransaction(
                    balance=balance,
                    employee=balance.employee,
                    leave_type=balance.leave_type,
                    transaction_type='legacy_conversion_used',
                    amount=balance.used,
                    effective_date=None,
                    reference="Legacy conversion from pre-C6.3 LeaveBalance.used"
                )
            )

    LeaveBalanceTransaction.objects.bulk_create(transactions)

def revert_legacy_balances(apps, schema_editor):
    LeaveBalanceTransaction = apps.get_model('leaves', 'LeaveBalanceTransaction')
    LeaveBalanceTransaction.objects.filter(
        transaction_type__in=['legacy_conversion_allocated', 'legacy_conversion_used']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_remove_leavetype_annual_allocation_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_legacy_balances, revert_legacy_balances),
    ]
