import React,{useEffect,useState}from'react';
import { Bell, Loader2, Plus, Send } from'lucide-react';
import { Card } from'../../components/Card';
import { announcementService,type Announcement } from'../../services/announcements';
import { useAuth } from'../../contexts/AuthContext';

export const AnnouncementsPage:React.FC=()=>{
 const {hasPermission}=useAuth(); const canManage=hasPermission('announcement.manage');
 const [items,setItems]=useState<Announcement[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null); const [form,setForm]=useState({title:'',body:'',is_published:true,expires_at:''});
 const load=()=>{setLoading(true);announcementService.list().then(x=>setItems(Array.isArray(x)?x:[])).catch(()=>setError('Unable to load announcements.')).finally(()=>setLoading(false));}; useEffect(load,[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError(null);try{await announcementService.create({...form,expires_at:form.expires_at||null});setOpen(false);setForm({title:'',body:'',is_published:true,expires_at:''});load();}catch{setError('Unable to save the announcement.');}};
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'var(--spacing-lg)',gap:12}}><div><h1 style={{margin:0,fontSize:'var(--font-size-2xl)'}}>Announcements</h1><p className="text-muted" style={{marginTop:4}}>Organization communications with controlled publishing and audit history.</p></div>{canManage&&<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/>New announcement</button>}</div>
 {error&&<div style={{color:'var(--color-status-danger)',marginBottom:12}}>{error}</div>}
 {loading?<Card><div style={{padding:32,textAlign:'center'}}><Loader2 className="animate-spin" color="var(--color-primary)"/></div></Card>:items.length===0?<Card><div className="text-muted" style={{padding:24,textAlign:'center'}}>No published announcements.</div></Card>:<div style={{display:'grid',gap:'var(--spacing-md)'}}>{items.map(i=><Card key={i.id}><div style={{display:'flex',gap:12}}><Bell size={20} color="var(--color-primary)"/><div><h2 style={{fontSize:'var(--font-size-lg)',margin:0}}>{i.title}</h2><p style={{whiteSpace:'pre-wrap',margin:'8px 0'}}>{i.body}</p><small className="text-muted">{i.branch_name||'Organization-wide'} · {i.published_at?new Date(i.published_at).toLocaleString():'Draft'} · {i.created_by_name}</small></div></div></Card>)}</div>}
 {open&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'center',zIndex:1000}}><Card style={{width:'min(600px,calc(100vw - 32px))'}}><h2 style={{marginTop:0}}>New announcement</h2><form onSubmit={submit} style={{display:'grid',gap:12}}><input className="input-neumorphic" placeholder="Title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="input-neumorphic" placeholder="Message" required rows={6} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><label className="text-muted">Expires on <input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label><label><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Publish now</label><div style={{display:'flex',justifyContent:'flex-end',gap:8}}><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary"><Send size={16}/>{form.is_published?'Publish':'Save draft'}</button></div></form></Card></div>}</div>;
};
